-- MySQL Script generated by MySQL Workbench
-- Fri 24 Jul 2020 09:21:48 PM +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema earth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema earth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `earth` DEFAULT CHARACTER SET utf8 ;
USE `earth` ;

-- -----------------------------------------------------
-- Table `earth`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earth`.`country` (
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `continent` VARCHAR(32) NOT NULL,
  `surfaceArea` FLOAT NOT NULL,
  `population_country` INT NOT NULL,
  `gnp` FLOAT NOT NULL,
  `capital` INT NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `earth`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `earth`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `population` INT NOT NULL,
  `id_country` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`id_country`)
    REFERENCES `earth`.`country` (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
